apiVersion: apps/v1
kind: Deployment
metadata:
  name: psyderella
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psyderella
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: psyderella
    spec:
      containers:
      - name: psyderella
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 8000
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m