apiVersion: v1
kind: Service
metadata:
  name: psydarella-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
    - port: 8000
      targetPort: 8000
  selector:
    app: psyderella